# Generated by Django 4.2.3 on 2023-07-08 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='data_nascimento',
            field=models.DateField(null=True, verbose_name='Data de nascimento'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='link_whatsapp',
            field=models.TextField(null=True, verbose_name='Link do whatsapp'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='naturalidade',
            field=models.CharField(max_length=255, null=True, verbose_name='Naturalidade'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='nome',
            field=models.CharField(max_length=255, null=True, verbose_name='Nome'),
        ),
    ]
