# Generated by Django 4.2.3 on 2023-07-11 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_data_nascimento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='link_whatsapp',
        ),
        migrations.AddField(
            model_name='customuser',
            name='whatsapp',
            field=models.TextField(null=True, verbose_name='Whatsapp'),
        ),
    ]
