# Generated by Django 4.2.3 on 2023-07-11 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_customuser_link_whatsapp_customuser_whatsapp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='whatsapp',
            field=models.CharField(max_length=15, null=True, verbose_name='Whatsapp'),
        ),
    ]
